### Get ai service health
GET /health
Host: localhost:5001

### Generate product description
POST /generate/description 
Host: localhost:5001
Content-Type: application/json

{
    "name": "OLED webOS Evo ThinQ AI Smart TV",
    "tags": ["tv","entertament"]
}

### Generate product image
POST /generate/image 
Host: localhost:5001
Content-Type: application/json

{
    "name": "OLED webOS Evo ThinQ AI Smart TV",
    "description": "Experience the ultimate in visual brilliance with the LG 65 4K OLED Evo ThinQ AI smart TV. It comes with gaming features like NVIDIA G-Sync, AMD FreeSync Premium, and VRR to ensure enhanced gameplay. With a lightning-fast 0.1ms response time and a native 120Hz refresh rate, it delivers crisp and smooth imagery. Thanks to the intuitive AI features, accessing your favourite content is a breeze."
}
