### Get ai service health
GET /health
Host: localhost:5001

### Generate product description
POST /generate/description 
Host: localhost:5001
Content-Type: application/json

{
    "name": "Sony WH-CH520 On-Ear Bluetooth Headphones w/ Microphone - Black",
    "tags": ["headphones","weable"]
}

### Generate product image
POST /generate/image 
Host: localhost:5001
Content-Type: application/json

{
    "name": "Sony WH-CH520 On-Ear Bluetooth Headphones w/ Microphone - Black",
    "description": "Listen all day with the Sony WH-CH520 on-ear headphones. These headphones are powered with a 50-hour battery. It features a lightweight over-the-head band and padded cups to ensure optimal comfort, and the ten-metre Bluetooth range allows for easy connection to Bluetooth compatible devices. They’re also equipped with a built-in microphone for crisp, hands-free voice calls."
}
